### ISSUE TITLE
Tag Profiler not running

### ISSUE THREAD

**Issue by ericallam** [palkan/test-prof#1]
I'm running my rspec suite with `TAG_PROF=type bundle exec rspec` and there is no test-prof output. I've followed the installation instructions and added `test-prof` to the Gemfile, bundled, and added this configuration to by rails helper:

```ruby
require 'test-prof'

TestProf.configure do |config|
  # the directory to put artifacts (reports) in ("tmp" by default)
  config.output_dir = "tmp/test_prof"

  # use unique filenames for reports (by simply appending current timestamp)
  config.timestamps = true

  # color output
  config.color = true
end
```

I'm using Rails 5.0.4, rspec-rails 3.5.0, and test-prof 0.1.0.

**Comment by palkan** [comment]
Could you, please, show the whole `rails_helper.rb` (at least from the beginning 'till the TestProf configuration)?

Also, do you use Spring?

**Comment by ericallam** [comment]
@palkan well the `rails_helper.rb` is quite simple itself, but it imports all files in `spec/support` so the real "full" rails_helper.rb with everything required would be pretty large, but here is just the `rails_helper.rb` itself and the TestProf config is in `spec/support/test_prof.rb`:

```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'

require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
require 'byebug'

Dir[Rails.root.join('spec/support/**/*.rb')].each { |file| require file }

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.infer_spec_type_from_file_location!
end
```

Also, I am using Spring. I can't right now but will try to use TestProf with spring turned off in a bit to see if that makes a difference.

**Comment by ericallam** [comment]
Okay it turned out I wasn't using Spring, but it was in my Gemfile, which caused the `TestProf.activate!` method to never get called, which is why it wasn't running.
