### ISSUE TITLE
Add percentage and total test time to EventProf

### ISSUE THREAD

**Issue by palkan** [palkan/test-prof#100]
Add a percentage of time spent in the event (from the total test suite/group/example time)

Before:

```
[TEST PROF INFO] EventProf results for factory.create

Total time: 03:07.353
Total events: 7459

Something (./my_spec.rb:21) – 09:16.100 (7 / 3)
...
```

After:

```
[TEST PROF INFO] EventProf results for factory.create

Total time: 03:07.353 of 07:25:232 (42.02%)
Total events: 7459

Something (./my_spec.rb:21) – 09:16.100 (7 / 3) of 12:29:233 (74.13%)
...
```

**Comment by dmagro** [comment]
Hello there! May I take a look at this one?

**Comment by palkan** [comment]
Hi!

> May I take a look at this one?

Sure)

>  I'm trying to understand what do you mean by total test time.

That's the total time the test suite took (i.e. the sum of all examples total time spent).

**Comment by dmagro** [comment]
@palkan could you take a look at my PR?
