### ISSUE TITLE
Detect database_cleaner usage along with before_all

### ISSUE THREAD

**Issue by palkan** [palkan/test-prof#108]
Using `database_cleaner` along with `before_all` (and other group-wide helpers, e.g. `let_it_be`) could break things (see #107, #106).

We need to find a way to warn users about possible issues by printing a warning (or raising?):

```
Warning! Usage of database_cleaner could break before_all/let_it_be functionality.
Consider turning off or removing database_cleaner at all.

See https://test-prof.evilmartians.io/#/active_record_shared_connection.
```

When non-transactional strategy is used (i.e. truncation/deletion), it's better to raise an exception ('cause it would definitely break everything).

From #106  we can see that `:transaction` strategy could also be breaking; probably, the reason is that is used along with `transactional_fixtures = true`. Need to investigate these scenarios.

**Comment by zauzaj** [comment]
@palkan I think we can close this as I've fixed our issue with updating `test-prof` and it works really nice. Here is the DatabaseCleaner we're using:
```
RSpec.configure do |config|
  config.use_transactional_fixtures = false
  config.before(:suite) { DatabaseCleaner.clean_with(:truncation) }
  config.after(:suite) { DatabaseCleaner.clean_with(:truncation) }
  config.before(:all) { DatabaseCleaner.clean_with(:truncation) }
  config.around(:each) do |example|
    DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction
    DatabaseCleaner.cleaning { example.run }
    Capybara.reset_sessions!
  end
end
```
