### ISSUE TITLE
TestProf::BeforeAll::AdapterMissing ??

### ISSUE THREAD

**Issue by johncox00** [palkan/test-prof#123]
### Environment

**Ruby Version:**
2.4.0

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
`rails-5.1.3`
`rspec-3.6.0`
`factory_girl_rails-4.8.0`

**TestProf Version:**
`test-prof-0.7.4`

### What did you do?
```
# rails_helper.rb
require 'test_prof/recipes/rspec/let_it_be'
```
Global find-and-replace `let(:` with `let_it_be(:`.

### What did you expect to happen?

It would "just work"

### What actually happened?

Lots of this:
```
TestProf::BeforeAll::AdapterMissing:
  Please, provide an adapter for `before_all` through `TestProf::BeforeAll.adapter = MyAdapter`
# /Users/johncox/.rvm/gems/ruby-2.4.0@dont_fear/gems/test-prof-0.7.4/lib/test_prof/before_all.rb:24:in `rollback_transaction'
# /Users/johncox/.rvm/gems/ruby-2.4.0@dont_fear/gems/test-prof-0.7.4/lib/test_prof/recipes/rspec/before_all.rb:22:in `block in before_all'
```

Any thoughts? I feel like I'm just missing something simple in the documentation, but I've been through it several times.

**Comment by palkan** [comment]
Hi @johncox00,

Where did you put `require 'test_prof/recipes/rspec/let_it_be'`?

In order to automatically configure ActiveRecord (do you use ActiveRecord?) you should require `let_it_be` (and any other recipe) after loading the app (i.e. `require "<smth>/environment.rb"`).

Ref: https://github.com/palkan/test-prof/blob/e4d8e23664ae27bcc8eaaaefb5069edf240b5ce5/lib/test_prof/before_all.rb#L31

**Comment by johncox00** [comment]
@palkan, that was it. Thanks for the tip. Ended up moving the `require` down:

```
require 'simplecov'
SimpleCov.start do
  add_filter "/spec/"
  add_filter "/lib/tasks/"
  add_filter "/config/"
  add_filter "/app/models/data_import.rb"
  add_filter "/app/controllers/data_imports_controller.rb"
end
require 'spec_helper'
require_relative 'support/controller_macros'
require "cancan/matchers"
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
require_relative 'support/tasks'
require 'test_prof/recipes/rspec/let_it_be'
```

**Comment by Vuta** [comment]
> In order to automatically configure ActiveRecord (do you use ActiveRecord?) you should require let_it_be (and any other recipe) after loading the app (i.e. require "<smth>/environment.rb").

Hi @palkan, what if we are using something else, like `rom-rb` instead of active record?

**Comment by palkan** [comment]
@Vuta To use `let_it_be` / `before_all` with `rom-rb`, you need to add a custom adapter similar to ActiveRecord one: https://github.com/test-prof/test-prof/blob/master/lib/test_prof/before_all/adapters/active_record.rb

See https://test-prof.evilmartians.io/#/recipes/before_all?id=database-adapters
