### ISSUE TITLE
Use both let_it_be and create_default

### ISSUE THREAD

**Issue by Systho** [palkan/test-prof#125]
Hello, 

I'm trying to use both `let_it_be` and `create_default` in a test file and I have difficulties to do so because `create_default` is reset after each test.

My spec files looks like this : 

```
context "with a valid Foo" do
  it "does A" do ... end
  it "does B" do ... end
  it "does C" do ... end
end

context "with a valid Bar" do
  it "does A" do ... end
  it "does B" do ... end
  it "does C" do ... end
end


private
# In the end I'd like all my created records to belong to the same tenant
let_it_be(:tenant){ create_default(:tenant) }
```
My tenant is created before all test and is used for the first test but then FactoryDefault is cleared and my tenant is not used anymore as default for the other 5 tests.

Am I missing something ? How should I benefit from those two mechanisms ?

**Comment by palkan** [comment]
Hi!

FactoryDefault resets its state [after each example](https://github.com/palkan/test-prof/blob/92eb0aa8f750b8423c70554e0d752c8a9e501745/lib/test_prof/recipes/rspec/factory_default.rb#L7-L9).

So, what you can do for now:

- replace "require "test_prof/recipes/rspec/factory_default"` with `require "test_prof/factory_default"`
- call `TestProf::FactoryDefault.init` right after it
- write your own logic for resetting the defaults state, e.g.:

```ruby
RSpec.configure do |config|
  config.after(:each) do |ex|
    TestProf::FactoryDefault.reset unless ex.metadata[:factory_default] == :keep
  end
end
```

Then in your spec file:

```ruby
describe "smth", factory_default: :keep do
  let_it_be(:tenant){ create_default(:tenant) }
  
  # that should be called to avoid leaking factory objects
  after(:all) { TestProf::FactoryDefault.remove(:tenant) }

  context "with a valid Foo" do
    it "does A" do ... end
    it "does B" do ... end
    it "does C" do ... end
  end
end
```

**Comment by palkan** [comment]
@Systho Have you tried the code snippet above?

**Comment by Systho** [comment]
Hi @palkan , 

Yes it works but I still think that these 2 features should work together without a special hack. But it would mean that the FactoryDefault is able to store defaults for each test group context which is probably a heavy refactor.

For the moment, I think it might just be a good idea to state in the beautiful doc you made that those features are incompatible.

Thanks for your help !

**Comment by palkan** [comment]
> For the moment, I think it might just be a good idea to state in the beautiful doc you made that those features are incompatible.

Done!

Thanks

**Comment by cbliard** [comment]
Hi there,

Instead of using @palkan snippet, I used something like this and it seems to work:

```
describe "smth" do
  let_it_be(:tenant, refind: true) { create(:tenant) }
  
  before { set_factory_default(:tenant, tenant) }

  context "with a valid Foo" do
    it "does A" do ... end
    it "does B" do ... end
    it "does C" do ... end
  end
end
```

As `FactoryDefault` resets its state after each example, I call `set_factory_default` before each test instead with the object made persistent with `let_it_be`. This avoids any risk of leaking factory objects.

Is this approach valid or am I missing something obvious here?

**Comment by palkan** [comment]
> Is this approach valid or am I missing something obvious here?

Yeah, that's the correct approach; thanks!
