### ISSUE TITLE
NoMethodError: undefined method `dump' for nil:NilClass in ./lib/test_prof/ruby_prof/rspec.rb:21:in `example_finished'

### ISSUE THREAD

**Issue by 0xdevalias** [palkan/test-prof#126]
```
..snip..
# bin/rspec:9:in `load'
# bin/rspec:9:in `<main>'
#
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
# ------------------
# --- Caused by: ---
# NoMethodError:
#   undefined method `dump' for nil:NilClass
#   /Users/dev/foo/vendor/bundle/ruby/2.4.0/gems/test-prof-0.7.5/lib/test_prof/ruby_prof/rspec.rb:21:in `example_finished'
```

https://github.com/palkan/test-prof/blob/master/lib/test_prof/ruby_prof/rspec.rb#L21

### Tell us about your environment

**Ruby Version:** `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin18]`

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**

```
⇒  rspec --version
RSpec 3.7
  - rspec-core 3.7.1
  - rspec-expectations 3.7.0
  - rspec-mocks 3.7.0
  - rspec-rails 3.7.2
  - rspec-support 3.7.1
```

**TestProf Version:** `0.7.5`

**RubyProf Version:**

```
  gem 'ruby-prof',
    :git => 'https://github.com/ruby-prof/ruby-prof',
    :ref => 'a813bdd7891806cd26ec8c71ea6297827e07fa54',
    require: false
```

### What did you do?

Tried to run `rspec` on one of my spec files. I had`:rprof` set on my spec test case.

```
TEST_RUBY_PROF=multi bin/rspec ./spec/features/foo/bar_spec.rb:120
```

### What actually happened?

Got the above error

```
[5] pry(#<TestProf::RubyProf::Listener>)> whereami

From: /Users/dev/foo/vendor/bundle/ruby/2.4.0/gems/test-prof-0.7.5/lib/test_prof/ruby_prof/rspec.rb @ line 21 TestProf::RubyProf::Listener#example_finished:

    19: def example_finished(notification)
    20:   binding.pry
 => 21:   return unless profile?(notification.example)
    22:   notification.example.metadata[:rprof_report].dump(
    23:     notification.example.full_description.parameterize
    24:   )
    25: end

[6] pry(#<TestProf::RubyProf::Listener>)> notification.example.metadata[:rprof_report]
=> nil
```

**Comment by palkan** [comment]
Hi @0xdevalias,

Thanks for the report.

Could you please put the `binding.pry` on the next line (right after `return unless profile?(notification.example)`) and show me what's the contents of `notification.example.metadata`.

> I had `:rprof` set on my spec test case.

Did you add the tag to an example group or to a particular example?

**Comment by 0xdevalias** [comment]
The metadata is pretty huge, but in pry'ing it I can confirm that the `:rprof` key is `true`, and the `:rprof_report` key is `nil`.

It's set on a specific case, though it is nested through a few `context`'s, etc

```
it 'over the character limit shows error', :rprof do
  click_button 'Foo'
  find_field('bar').send_keys long_note
  click_button 'Save Note'
  expect(find('#notification-area')).to have_text 'Unable to save note'
end
```

**Comment by palkan** [comment]
Ok, I got it.

You're using `TEST_RUBY_PROF` env variable to specify the printer type, but it activates the _global profiling_ (the whole TestProf run).

It's not possible to profile separate examples when global profiling is active _(todo: update docs)_.

In order to specify the printer without enabling global profiling you should use `TEST_RUBY_PROF_PRINTER=multi` variable.

**Comment by 0xdevalias** [comment]
Ah, that would make sense. Could be cool to have it fail fast with a descriptive error in that case too maybe?

From memory, when I was looking at the docs I thought it weird that `TEST_RUBY_PROF=1` would run global, but then the only documented env var for setting the printing also seemed to be `TEST_RUBY_PROF=multi`

I know the docs link to the file that says where all the env vars are, but would it be possible to maybe list them out explicitly in the docs too?

**Comment by palkan** [comment]
I just updated the docs and added a warning for this case: https://github.com/palkan/test-prof/commit/d71caaf9b23211dc2f090e1ff4f3db1b00d03a24
