### ISSUE TITLE
Spec with `let_it_be` fails after the first example when run after capybara JS spec

### ISSUE THREAD

**Issue by engwan** [palkan/test-prof#132]
### Tell us about your environment

**Ruby Version: 2.6.2**

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever): RSpec 3.8, FactoryBot 4.8.2, Rails 5.1.7**

**TestProf Version: 0.8.0**

### What did you do?

I have a spec file that uses `let_it_be`. If I run this test on its own, it passes.

When I run a JS feature spec (That uses capybara with chrome driver) and then the spec, the spec fails after the first example.

### What did you expect to happen?

The spec passes even if run together with a JS spec before it.

### What actually happened?

I get errors about missing data and a `!!! before_all transaction has been already rollbacked and could work incorrectly` at the end so that means the `before_all` transaction was rolled back prematurely after the first example.

I used `pry` to step through the code and find out where it's happening. In `ActiveRecord::TestFixtures#teardown_fixtures` which is run after each example, `ActiveRecord::Base.clear_active_connections!` is called.

If the test is run individually, `ActiveRecord::Base.connection.open_transactions` remains at `1` even after that is called.

When run after the JS test, `ActiveRecord::Base.connection.open_transactions` becomes `0` in the teardown for the non-JS spec's first example. Meaning the transaction for `before_all` was rolled back. I'm not really sure why.

I tried enabling AR logging and I don't see any unexpected explicit rollback.

UPDATE:

I've narrowed it down to running a JS spec that uses `DatabaseCleaner`'s delete strategy. When running a non-JS spec with `deletion` it works fine.

I know you don't really support the use of `let_it_be` with `DatabaseCleaner`, but that seems to work fine except for this case with JS tests.

Any idea what might be happening here?

**Comment by palkan** [comment]
Do you have smth like:

```ruby
config.after(:each, js: true) do
  DatabaseCleaner.clean
end
```

With this setup `let_it_be` / `before_all` cannot work (since the DB is cleaned after each example and not group).

Do you have `config.transactional_tests` set to `true` or `false`?

The best option would be to avoid using `database_cleaner` even for JS specs: since Rails 5.1 the DB connection is shared between threads in tests, thus we can use transactions to clear the state (`config.transactional_tests = true`) and no need to clean DB manually.
