### ISSUE TITLE
Issue with stubbing methods using before_all/let_it_be

### ISSUE THREAD

**Issue by zauzaj** [palkan/test-prof#145]
Hi, 
In the last couple of months, we've introduced `test-prof` into our test environment and I have to say it works really nice. Great job guys 👏 

What I was wondering is if we can consider this use case: 
`spec_helper.rb` 

```
config.before(:each) do 
  $redis = MockRedis.new
  allow($redis).to receive(:publish).and_return(true)
end
```

in `consultation.rb` we have callback where we do 
```$redis.publish "notification", params ```

in  specs/models/consultation.rb: 
```
let_it_be(:consultation) { create(:consultation) } 
....
```
This unit specs are going to fail with following error
```
NoMethodError:
        undefined method `publish' for #<MockRedis::Database:0x005649957bbdf0>
```
The reason is - consultation is created before we do stubbing $redis. When we've used `let/let!` in our unit specs it was good. 

@palkan What do you think?
It might be good to consider stubbing way inside ruby-prof hooks even Mr. Chelimsky says differently 
https://github.com/rspec/rspec-mocks/pull/115/files

**Comment by palkan** [comment]
We recently added `before_all` hooks, which could be used here: https://test-prof.evilmartians.io/#/before_all?id=hooks

Try smth like:

```ruby
TestProf::BeforeAll.configure do |config|
  config.before(:begin) do
    allow($redis).to receive(:publish).and_return(true)
  end
end
```

See also how Discourse use them: https://github.com/discourse/discourse/blob/6fec4982d903cbb088f95b5dcae7b67f52a90e99/spec/rails_helper.rb#L134

**Comment by zauzaj** [comment]
@palkan Thanks for this suggestion, but unfortunately this is possible only for ruby => 2.4 and we're currently on 2.3.1. 
As we're currently in rails upgrading I have to do step by step 😞  At least I will try to have some patch for this hooks. 

Thank again !

**Comment by zauzaj** [comment]
Hey again 😄 

I just come to the point to use `TestProf::BeforeAll`, but seems it doesn't work. I've tried what you sent ☝️ but I'm getting weird error:

```

**Comment by palkan** [comment]
> I can't stub/mock anything in before(:begin) as always same error/warning raised

Right. This hook is executed outside of the example lifecycle and thus has no access to mocking helpers.
What is `MockRedis`? Can't you just define `def publish; true; end` inside? Why mocking at all?

> If we move everything to let_it_be, we don't really need database_cleaner, but how actually data would be cleaned between examples in order to keep specs isolated?

The answer is—database transactions.
`let_it_be` uses `before_all` under the hood to wrap the whole RSpec _context_ (everything inside `describe ..` or `context`) into a transaction; thus at the end of this group execution, the transaction is rollback and no date stay in the DB.
The built-in `config.use_transactional_fixtures = true` does the same but at a single test level.

If you're using Rails older than 5.1, you need to add [this patch](https://test-prof.evilmartians.io/#/active_record_shared_connection) to make your browser tests play well with transactions.

**Comment by zauzaj** [comment]
Hey, thanks for the answer. Regarding `database transactions` I get the point now. So for now as we're dealing only with unit, controller & request specs our database cleaner does the job pretty well. 

Another part, regarding mocking redis I've solved it today with 
```
require "rspec/mocks/standalone"
.....
TestProf::BeforeAll.configure do |config|
  config.before(:begin) do
    $redis = MockRedis.new
    allow($redis).to receive(:publish).and_return(true)
  end
end
```
and it does work pretty well. But I agree it could be just opened and method defined, very nice catch 😄 

Anyway I think so far everything goes pretty good and I'm moving on with test-prof 🚀 so we can close the issue ticket now. 

Thanks for support!

**Comment by palkan** [comment]
> everything goes pretty good and I'm moving on with test-prof

Sounds good. Glad to help) If you find some interesting with test-prof (unexpected bottlenecks or huge speed improvements), don't hesitate to share your story: https://github.com/palkan/test-prof/issues/73
