### ISSUE TITLE
before_all transaction has been already rollbacked and could work incorrectly

### ISSUE THREAD

**Issue by samstickland** [palkan/test-prof#146]
I'm getting a few of these error messages:

`!!! before_all transaction has been already rollbacked and could work incorrectly`

Any idea how I should go about debugging them, or more info as to the meaning?

**Comment by samstickland** [comment]
OK, I see in the source code that this means that the open transaction count was zero when it tried to roll it back.. Hmmm....

I'll see if I can consistently reproduce this.

**Comment by samstickland** [comment]
OK, it's not easily reproducible unfortunately.. I'll keep digging and see if I can find out more info.

Details are:

ruby: 2.5.1
test-prof: 0.9.0
rails: 5.1.6
rspec: 3.7.0

**Comment by palkan** [comment]
This warning means that there are no open transaction known to test-prof (more precisely, to Active Record).

That usually happen not because the transaction has been rollbacked/committed manually but because of the multi-threading race conditions (which are not easy to catch).

Some question that could help:
- Do you have `use_transactional_fixtures = true` in RSpec configuration? 
- Do you use DatabaseCleaner?
- Do you use `async` adapters for ActiveJob/ActionCable?
- Anything else that could use threads inside `before_all`?

**Comment by samstickland** [comment]
Aha, I have a reproducible test that has shed a little bit of light on things. Something to do with our DatabaseCleaner based feature tests is leaving transactions_fixtures set to false, even though it's set back to true after running a feature test.

```
rspec ./spec/concepts/assignments/op/cancel_spec.rb[1:1:1,1:2:4] ./spec/concepts/partners/features/recommend_spec.rb[1:1] --seed 8628 -fdoc
Run options: include {:ids=>{"./spec/concepts/assignments/op/cancel_spec.rb"=>["1:1:1", "1:2:4"], "./spec/concepts/partners/features/recommend_spec.rb"=>["1:1"]}}

Randomized with seed 8628

partners
  recommend a partner, view errors, correct and send email

Assignments::Op::Cancel
  when the policy does not permit cancel
    should be policy failure
  when the policy permits cancel
    marks the Assignment as cancelled (FAILED - 1)
```

The tests ran for `Assignments::Op::Cancel` are simply:

```
    let(:user) { User.new }
    let_it_be_with_refind(:assignment) { FactoryGirl.create :assignment, :with_assigned_personnel }

    let(:reason) { FFaker::HipsterIpsum.sentence }
    let(:params) { { id: assignment.id, assignment: { cancelled_reason: reason } } }

    subject(:cancel) do
      Assignments::Op::Cancel.(params: params, current_user: user)
    end

    context 'when the policy does not permit cancel' do
      before { stub_policy AssignmentPolicy, user, assignment, cancel?: false }

      it { is_expected.to be_policy_failure }
    end

    context 'when the policy permits cancel' do
      before { stub_policy AssignmentPolicy, user, assignment, cancel?: true }

      it { is_expected.to be_success }
    end
```

Debugging through that shows that on the second test Assignments::Op::Cancel that the Assignment record genuinely doesn't exist.

The tests pass if the feature test isn't ran before hand, which points the finger at some transactional/DatabaseCleaner issues (we haven't yet moved to system tests).

These are the relevant bits of our DatabaseCleaner / RSpec setup:

```
    config.use_transactional_fixtures = true

    config.before(:suite) do
      DatabaseCleaner.clean_with :truncation, except: %w[ar_internal_metadata]
      DatabaseCleaner.strategy = :deletion
    end

    config.around(:each, type: :feature, js: true) do |example|
      self.use_transactional_tests = false

      DatabaseCleaner.cleaning do
        example.run
      end

      self.use_transactional_tests = true
    end
```

If we comment out the line `self.use_transactional_tests = false` then the tests above pass.. Which is very odd - why didn't the last line turn them back on again?

**Comment by samstickland** [comment]
Interestingly commenting out the database cleaner lines still produces the same error. That is with this code:

```
    config.around(:each, type: :feature, js: true) do |example|
      self.use_transactional_tests = false

      example.run

      self.use_transactional_tests = true
    end
```

**Comment by samstickland** [comment]
Interesting.. the problem only occurs with `config.around`, this works correctly:

```
    config.before(:each, type: :feature, js: true) do
      self.use_transactional_tests = false
    end

    config.after(:each, type: :feature, js: true) do # |example|
      DatabaseCleaner.clean_with :truncation, except: %w[ar_internal_metadata]
      self.use_transactional_tests = true
    end
```

**Comment by palkan** [comment]
> the problem only occurs with config.around

Maybe, `example.run` raises an exception? and the code never reaches `self.use_transactional_tests = true`.

Also, have you tried to remove the whole `js: true` block? (both `before` and `around` hooks). Since you're using Rails 5.1, JS specs should re-use the same DB connection and you can use transaction fixtures (see https://github.com/rails/rails/pull/28083 or https://test-prof.evilmartians.io/#/active_record_shared_connection?id=active-record-shared-connection).

**Comment by samstickland** [comment]
Yeah, I tried it in the debugger and example.run wasn't raising an exception.

Our plan is to move to using system tests with a shared DB connection, but not there yet. We were using rspec-nested_transactions and our own helper to provide similar functionality to `let_it_be`, but that gem doesn't work with shared transactions in Rails 5.1 and the author doesn't really use Rails anymore.

So step 1 is migrate from our custom helper + rspec-nested_transactions to test-prof
Step 2 will be to move to Rails 5.1 with system tests

**Comment by palkan** [comment]
> Step 2 will be to move to Rails 5.1 with system tests

It's not necessary to migration to system tests to use a shared DB connection. This feature works in all types of tests, not only system ones.

**Comment by samstickland** [comment]
Oh that's interesting, that implies we've been running that feature already without knowing it.. Hmm... It doesn't explain why when we first tried to move to system tests with the rspec-nested_transactions gem still active that the tests hung though. I'd need to investigate that again.

**Comment by palkan** [comment]
Closing for now. Feel free to re-open if you have any further questions.
