### ISSUE TITLE
Reload: true with create_list

### ISSUE THREAD

**Issue by fabriciofreitag** [palkan/test-prof#148]
Is there a way of using `let_it_be` with reload: true along with `FactoryBot's` `create_list`?

**Comment by palkan** [comment]
Right now this is not supported. Sounds like a good addition.

We can take arrays into account here: https://github.com/palkan/test-prof/blob/50f814526b2f0f50a44d21891e560e95c8b83253/lib/test_prof/recipes/rspec/let_it_be.rb#L73-L74

(and in `refined` as well)
