### ISSUE TITLE
Support for Ruby 2.2.x

### ISSUE THREAD

**Issue by simonewebdesign** [palkan/test-prof#15]
Hi, would it be possible to provide support for Ruby 2.2.x? At the moment I'm using Ruby 2.2.5p319 and when I run bundle I get:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    test-prof was resolved to 0.1.0, which depends on
      ruby (>= 2.3.0)
```

**Comment by palkan** [comment]
Hi, @simonewebdesign !

[Investigating...](https://travis-ci.org/palkan/test-prof/builds/269998017).

**Comment by simonewebdesign** [comment]
Thank you!
