### ISSUE TITLE
NoMethodError: undefined method `parameterize' for #<String:0x00007f99fdb429d8>

### ISSUE THREAD

**Issue by Justin-W** [palkan/test-prof#150]
### Tell us about your environment

**Ruby Version:**
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
RSpec 3.8
  - rspec-core 3.8.0
  - rspec-expectations 3.8.2
  - rspec-mocks 3.8.0
  - rspec-support 3.8.0

**TestProf Version:**
test-prof (0.9.0)
    Author: Vladimir Dementyev
    Homepage: http://github.com/palkan/test-prof
    License: MIT
    Installed at: ~/.rvm/gems/ruby-2.6.3

### What did you do?

Following the test-prof [setup instructions](https://test-prof.evilmartians.io/#/getting_started), I added the following code below in my spec_helper.rb file. (Note that the test-prof Getting Started page says nothing about needing any require statements.)

```
# HACK: test-prof fails (calling String#parameterize) without the explicit require below.
# Error: ~/.rvm/gems/ruby-2.6.3/gems/test-prof-0.9.0/lib/test_prof/ruby_prof/rspec.rb:21:in `example_finished': undefined method `parameterize' for #<String:0x00007f99fdb429d8> (NoMethodError)
# see: [Active Support Core Extensions#cherry-picking-a-definition — Ruby on Rails Guides](https://guides.rubyonrails.org/active_support_core_extensions.html#cherry-picking-a-definition)
# require 'active_support/core_ext/string/inflections.rb'
require 'ruby-prof'
require 'test-prof'

#...

# configure test-prof
TestProf.configure do |config|
  # the directory to put artifacts (reports) in ('tmp/test_prof' by default)
  config.output_dir = 'temp/test_prof'

  # use unique filenames for reports (by simply appending current timestamp)
  config.timestamps = true

  # color output
  config.color = true
end
```

### What did you expect to happen?

For rspec to run without errors, and for test-prof to generate some reports.

### What actually happened?

After my 7 spec examples finished (and after SimpleCov generated it's own report), 7 error Tracebacks were printed. All 7 errors were identical:

`~/.rvm/gems/ruby-2.6.3/gems/test-prof-0.9.0/lib/test_prof/ruby_prof/rspec.rb:21:in `example_finished': undefined method `parameterize' for #<String:0x00007f99fdb429d8> (NoMethodError)
`

However, if I add the (commented-out above) require statement for the active_support core_ext extension, running the same rspec command doesn't produce those errors.

My guess is that test-prof probably works fine if that core_ext extension happens to be required by the user's own code (and which is probably true for any Rails project). However, for compatibility with non-Rails projects, it seems like test-prof should be configured to enable that extension automatically (either during test-prof gem installation, or else at runtime), without requiring the user to explicitly enable the extension in their own gem code.

**Comment by palkan** [comment]
Thanks for the report!

> test-prof probably works fine if that core_ext extension happens to be required by the user's own code

Looks so. We shouldn't rely on core_ext here. The best way to fix this would be to drop a refinement adding `String#parameterize` if it's not defined.

The same problem with stackpof: https://github.com/palkan/test-prof/blob/7b35213fc4062ecb9073d135838a40b516ef089f/lib/test_prof/stack_prof/rspec.rb#L22
