### ISSUE TITLE
File name too long @ rb_sysopen - ... (Errno::ENAMETOOLONG) errors

### ISSUE THREAD

**Issue by Justin-W** [palkan/test-prof#151]
### Tell us about your environment

**Ruby Version:**
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
RSpec 3.8

rspec-core 3.8.0
rspec-expectations 3.8.2
rspec-mocks 3.8.0
rspec-support 3.8.0

**TestProf Version:**
test-prof (0.9.0)

### What did you do?
ran rspec, with test-prof configured as shown in the Getting Started page.

### What did you expect to happen?
For rspec to run without errors, and for test-prof to generate some reports.

### What actually happened?
test-prof generated some reports successfully, but report generation failed for most reports, as those reports' generated file names were too long.

Excerpts from the rspec output:

```
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-runs-without-error-801089.html
          runs without error
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-exists-801089.html
              exists
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-is-a-dir-801089.html
              is a dir
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-exists-801089.html
                    exists (FAILED - 1)
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-is-a-dir-801089.html
                    is a dir (FAILED - 2)
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-runs-without-error-801089.html
                      runs without error (FAILED - 3)
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-exists-801089.html
                          exists (FAILED - 4)
...
                                                                  runs without error (FAILED - 15)
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-exists-801089.html
                                                                      exists (FAILED - 16)
...[TEST PROF INFO] RubyProf report generated: temp/test_prof/ruby-prof-report-graph_html-wall-bin-terra-test-prof-c10c-v1b-has-behavior-se-dryrun-sh-dryrun-sh-c10c-v1b-false-has-behavior-se-golden-dir-obj-tfwd-rspec-c10c_v1b-is-a-dir-801090.html
                                                                      is a dir (FAILED - 17)
```

My test suite is data-driven, and uses nested Shared Examples, so many of the examples' names are extremely long, and these errors are quite explainable given that the report names are derived directly from the examples' full names.

However, irrespective of the explanation, the errors do prevent the reports from being saved, and therefore prevent me from accessing the data in any of the reports that failed to save.

And given the implementation of rspec, I can't really change the spec suite so that the examples' names are short enough. To do so would make the regular rspec output unusable for it's normal purpose (i.e. reporting test results).

It would be better if the test-prof code that dynamically generates the report filenames were enhanced to be able to detect overly-long file names, and to modify those file names so that they are valid.

[This PR](https://github.com/thoughtbot/paperclip/pull/1345) (from a different repo) demonstrates a simplistic form of such a fix.

If test-prof were able to truncate the 'default' file name, and then append a unique Integer or ID, that would probably work.

If such a truncation fix were implemented, it would likely become difficult to find the reports associated with any specific example whose reports had been truncated. So if test-prof could also keep track of the original example names, and the corresponding report file names, and generate a single 'index.txt' or 'index.html' file, that would make it easier to determine which reports correspond with specific tests. Such an index file could be generated either after all other reports (at the end of testing/profiling), or else incrementally as each report file is generated.

**Comment by Justin-W** [comment]
Please let me know if there are any workarounds for this issue. Thanks.

**Comment by palkan** [comment]
Thanks for the report!

I have an idea: what about using filename + line of code (`metadata[:location]`) as the source of the report name in case of a very long description? WDYT?

**Comment by Justin-W** [comment]
I think that seems like a very reasonable suggestion for a base prefix. However, the same line of code will likely generate multiple examples (due to the data-driven aspect), so you'd still need something that acts as a UID for each example.

**Comment by palkan** [comment]
> you'd still need something that acts as a UID for each example.

We already have an option to add timestamps to reports names: https://test-prof.evilmartians.io/#/getting_started?id=configuration

That should work, I think.

**Comment by Justin-W** [comment]
> We already have an option to add timestamps to reports names

That's a good tip, but also not guaranteed unique. Since the accuracy of timestamps is often only to the millisecond (depending on OS), it seems very probable that examples could end up with non-unique timestamps.

However, in the #artifact_path method (~/.rvm/gems/ruby-2.6.3/gems/test-prof-0.9.0/lib/test_prof.rb:85) where you call #with_timestamps, it seems like you could call a #with_ids method that would append an auto-incrementing Integer representing the ID of report. E.g. The 7th report would have 7 appended.

Or you could have the Listener classes' notification handlers call some method that would idempotently generate a UID based on the full_description of each example, so that multiple reports for the same example would be appended with the same UID. This would be preferable, IMO.

**Comment by palkan** [comment]
Hey @Justin-W,

Check out this PR: #154.

I ended up with the following:
- Example ID (`spec/path/to/example.rb:[1:2:3]`) is used for reports name generation by default.
It should be short enough for most cases and also allows to identify the example.
- Since this covers most but not all cases, there is a way to use a custom generator:

```ruby
TestProf::RubyProf::Listener.report_name_generator = <any callable>
```

For example, you can do something like:

```ruby
TestProf::RubyProf::Listener.report_name_generator = ->(example) {
  example.full_description.parameterize.then do |name|
    next  name if name < 200 # we need some characters for ruby prof settings prefix

    "#{name[0..150]}-#{Digest::SHA1.hexdigest(name)}"
  end
}
```

**Comment by Justin-W** [comment]
Looks great @palkan! Thanks!
