### ISSUE TITLE
Transactions doesn't seem to rollback for multiple databases

### ISSUE THREAD

**Issue by arielscherman** [palkan/test-prof#152]
### Tell us about your environment

**Ruby Version:** ruby 2.5.0p0

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
- RSpec v3.7.0
- FactoryBot v4.8.2
- Rails v5.2.2

**TestProf Version:** v0.9.0

### What did you do?

I am adding `test-prof` to my project to be able to use `let_it_be`. I'm using the Rails version that allows transactional tests with a shared connection when using feature tests with Capybara.
Having a controller test, I changed from this:

```ruby
let(:foo) { create(:foo) }
```

To this:

```ruby
let_it_be(:foo) { create(:foo) }
```

The `Foo` model has a `belongs_to` association to a model `Bar` from a different database:

```ruby

class Foo < ActiveRecord::Base
  belongs_to :bar
end

class Bar < ActiveRecord::Base
  establish_connection "other_database_#{Rails.env}".to_sym
end
```

When I was using just `let(:foo)`, given I have `config.use_transactional_fixtures = true`, both records were destroyed after every run.
After I changed to `let_it_be(:foo)`, It works on the first run, but afterwards I get an error when trying to create the `Foo` record, because it says a `Bar` already exists with that name.
I added a `binding.pry` and in fact it looks like a record is in the database (in the first line of the test).
I started resetting the test database and again, it works the first time and fails afterwards.

### What did you expect to happen?

I would have expected the transaction to rollback all records, no matter the database.

### What actually happened?

Even though the `Foo` record was cleared as expected, that didn't happen with `Bar`.

Do you have any idea of what's going on? Is this a known issue?

**EDIT 07/27**
In case this helps. I've just also tried doing this:

```ruby
before_all do
  @bar = create(:bar)
end
```

And It's definitely not rolling back the transaction for the other database. That's not the case for creating records on the main database.

**Comment by palkan** [comment]
> It's definitely not rolling back the transaction for the other database

Yeah, because we don't know about other databases 🤷🏻‍♂️.

We should check whether it's possible to get this information (all the _active_ databases) from ActiveRecord. I think, it should be possible in Rails 6, but not sure about Rails 5.

For now, you can try to use [before_all hooks](https://test-prof.evilmartians.io/#/before_all?id=hooks) to begin/rollback another database's transactions like this:

```ruby
TestProf::BeforeAll.configure do |config|
  config.after(:begin) do
    Bar.connection.begin_transaction(joinable: false)
  end

  config.before(:rollback) do
        Bar.connection.rollback_transaction
  end
end
```
