### ISSUE TITLE
Unknown let_it_be modifiers were used: reload

### ISSUE THREAD

**Issue by CharlieIGG** [palkan/test-prof#167]
### Tell us about your environment

**Ruby Version:** 2.6.1

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec

**TestProf Version:** 0.10.1

### What did you do?
Ran RSpec using the `let_it_be` helper, with the `reload: true` option.

### What did you expect to happen?
Expect the specs to run as normal.

### What actually happened?
I got the following runtime error: 
`Unknown let_it_be modifiers were used: reload`

**Comment by palkan** [comment]
That had likely happened because `let_it_be` were required before the Rails app. We only activate `reload` and `refind` modifiers if ActiveRecord has already been loaded.

From the [docs](https://test-prof.evilmartians.io/#/let_it_be?id=caveats-amp-modifers):

> make sure that you require let_it_be after active_record is loaded (e.g., in rails_helper.rb after requiring the Rails app); otherwise the refind and reload modifiers are not activated.

**Comment by CharlieIGG** [comment]
I did read that, and what baffled me is that the place in which I was requiring it seemed to work at first, but then not. 

Putting the `require` at the end of the `rails_helper.rb` fixed the issue. Thank you @palkan .
