### ISSUE TITLE
Rubocop fails to run after update to v0.11.0

### ISSUE THREAD

**Issue by FraDim** [palkan/test-prof#173]
### Tell us about your environment

**Ruby Version:** 2.6.5

**Framework Version:** RSpec v3.9 testing Rails app

**TestProf Version:** 0.11.0

**Rubocop Version:** 0.79.0

### What did you do?

Upgraded to the new 0.11.0 version.

### What did you expect to happen?

Rubocop to run successfully.

### What actually happened?

Rubocop failed to run with the following output:

```
Configuration file not found: vendor/bundle/ruby/2.6.0/gems/test-prof-0.11.0/config/default.yml
```

As [indicated in the documentation](https://test-prof.evilmartians.io/#/rubocop), my `.rubocop.yml` contains:

```yaml
require:
  - 'test_prof/rubocop'
```

It looks like the [`config/default.yml`](https://github.com/palkan/test-prof/blob/bd494366c427b5bb0ff5a56a3fb142b838f45c3c/config/default.yml) is not included in the [`test-prof.gemspec`](https://github.com/palkan/test-prof/blob/bd494366c427b5bb0ff5a56a3fb142b838f45c3c/test-prof.gemspec#L31-L32).

**Comment by palkan** [comment]
Thanks for letting me know! And sorry for that. Fixed and released in 0.11.1.
