### ISSUE TITLE
`AggregateFailures` cop has been renamed to `AggregateExamples` Error

### ISSUE THREAD

**Issue by sallesma** [palkan/test-prof#192]
### Tell us about your environment

**Ruby Version:** 2.7.1

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec 3.9.0

**TestProf Version:** 0.11.3

### What did you do?

I added  `  - test_prof/rubocop` to my rubocop config
along with
```
RSpec/AggregateExamples:
  AddAggregateFailuresMetadata: false
```

I am using overcommit to trigger a check on all changed files in a before-commit hook
My rubocop config enables all cops by default. I then disable those I don't want

### What did you expect to happen?

I expected overcommit to run only `RSpec/AggregateExamples` because it is the only one referenced in the documentation

### What actually happened?

I got this weird message
```
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
`AggregateFailures` cop has been renamed to `AggregateExamples`.
```

And it took me a while to understand what `AggregateFailures` was. I had to dig the code to understand that this is a deprecated cop to be removed later
(Or at least that's why I understand from https://github.com/palkan/test-prof/blob/master/config/default.yml)

So I disabled it manually.
But maybe the documentation could warn this?

**Comment by palkan** [comment]
That's the overcommit issue: https://github.com/sds/overcommit/issues/511

We print a deprecation warning, since the cop has been renamed (though the older one still works). But Overcommit tries to parse the output for some reason 🤷🏻‍♂️
