### ISSUE TITLE
Order of truncating tables in after(:suite) for AnyFixture

### ISSUE THREAD

**Issue by AlexVPopov** [palkan/test-prof#26]
Say you have verious levels of nesting of models:

```ruby
class Foo < ApplicationRecord
  has_many :bars, dependent: :destroy
end

class Bar < ApplicationRecord
  belongs_to :foo
  has_many :bazs, dependent: :destroy
end

class Baz < ApplicationRecord
  belongs_to :bar
end
```

The logical thing to do is to first delete all the `bazs`, then the `bars` and finally the `foos`. If this order is not respected, one might potentially get an error like this one:

```ruby
ActiveRecord::InvalidForeignKey:
  PG::ForeignKeyViolation: ERROR:  update or delete on table "products" violates foreign key constraint "fk_from_subscriptions_to_products" on table "subscriptions"
  DETAIL:  Key (id, facility_id)=(1, 1) is still referenced from table "subscriptions".
  :
              DELETE FROM "products"
```

What do you think? Is it feasible to build some logic for the order of the deletion of tables?

**Comment by sponomarev** [comment]
The tables will be cleaned in the reverse order of entities creation which is logical and has to cover all the cases. It was fixed in #2. Do you see any edge cases and provide a way how to reproduce them?

**Comment by palkan** [comment]
@AlexVPopov 

>  reproduce my edge case into a sample app.

It should be easy to write a reproduction script using our specs (see https://github.com/palkan/test-prof/tree/master/spec/bugs). Feel free to add a failing reproduction spec and propose a PR.

**Comment by AlexVPopov** [comment]
O.K., I'll try and reopen this, thank you!

**Comment by AlexVPopov** [comment]
@palkan @sponomarev O.K., I caught my bug, so here is what was happening:

My baz context looked like this:

```ruby
shared_context 'baz' do
  before(:all) do
    another_bar = Fabricate(:baz, foo: @foo)

    @baz = TestProf::AnyFixture.register(:baz) do
      Fabricate(:baz, foo: @foo, bar: another_bar)
    end
  end

  let(:baz) { foo.bazs.find(@baz.id) }
end
```

and in one spec file I had:

```
include_context 'foo'
include_context 'baz'
```

At this point `tables_cache.keys #=> ['foos', 'bazs']`.

In another spec file I finally had:

```ruby
include_context 'bar'
```

which led to `tables_cache.keys #=> ['foos', 'bazs', 'bars']` and hence the foreign key error. I guess the moral of the story is: don't create records within `AnyFixture`, whose associations are also not created within `AnyFixture` (as was the case with `another_product`).

**Comment by palkan** [comment]
@AlexVPopov  I guess you mean `another_bar = Fabricate(:bar, foo: @foo)`, not `Fabricate(:baz)`?

Then yes, using _externally_ created resources within `AnyFixture` might not work. But it looks like a _bad practice_, doesn't it?)

Anyway, we can improve `AnyFixture` to handle such cases (e.g. by disabling referential integrity, like `DatabaseCleaner` [does](https://github.com/DatabaseCleaner/database_cleaner/blob/master/lib/database_cleaner/active_record/deletion.rb#L99)).

But for now it would be great to add a note about such cases to the guide. Would you like to propose a PR?

**Comment by AlexVPopov** [comment]
Yes, bar, I updated my comment. Sure, I'll do a PR.
