### ISSUE TITLE
TagProf empty output

### ISSUE THREAD

**Issue by rtrv** [palkan/test-prof#39]
**Ruby 2.3.4**

**Rails 4.2.0, RSpec 3.1.0**

**TestProf 0.4.0**

I run `TAG_PROF=type rspec`, and its output contains just table headers: 

```type          time   total  %total   %time           avg```

And nothing after that. I've tried with configuration from "Pro-Tip: More Types" and without it, results are the same.

**Comment by palkan** [comment]
I've checked different RSpec versions and it turned out that works only since version 3.4.0. Need more time to investigate what exactly has changed and how to fix it.

**Comment by palkan** [comment]
Fixed and released as 0.4.1
