### ISSUE TITLE
Broken specs after installing 

### ISSUE THREAD

**Issue by nononoy** [palkan/test-prof#43]
Ruby 2.2.5
Rspec, factory girl, capybara
-------------------------------------------------------------
After installing test-prof 37 broken specs appeared:
412 examples, 37 failures, 7 pending
After uninstalling test-prof:
412 examples, 0 failures, 7 pending
The most common error - deadlock
```
ActiveRecord::StatementInvalid:
        PG::TRDeadlockDetected: ERROR:  deadlock detected at character 13
        DETAIL:  Process 11977 waits for RowExclusiveLock on relation 5270960 of database 5270706; blocked by process 30236.
        Process 30236 waits for ShareRowExclusiveLock on relation 5270996 of database 5270706; blocked by process 11977.
        HINT:  See server log for query details.
````

**Comment by nononoy** [comment]
and also it is not working at all. No reports at rails 4.1, rspec 3,4

**Comment by palkan** [comment]
What profiler do you use? How do run your tests? Need more info.

**Comment by nononoy** [comment]
for example:
```
FPROF=flamegraph rspec spec/models/
 ```
i don't see any reports, just Rspec report, don't see test-prof default folder ('tmp/test-prof') - it is not existed. Maybe I missed something important?

**Comment by nononoy** [comment]
in my first issue with broken specs after installing test-prof - i used simple 
```
rspec spec/*
```
without any test-prof env variables

**Comment by palkan** [comment]
> FPROF=1 rspec
> did not produced reports, too

Do you see "FactoryProf enabled ..." in your console?

> in my first issue with broken specs after installing test-prof - i used simple
rspec spec/*
without any test-prof env variables

Hm, that strange; test-prof is no-op if you do not require something either in your code or through env variables.
Do you use Spring? Have you tried to reload it?

**Comment by nononoy** [comment]
> Do you see "FactoryProf enabled ..." in your console?
No, i don't
> Do you use Spring? Have you tried to reload it?
No, spring only in develoment environment. 

Also i figured out broken specs issue, sorry, my local bug.

**Comment by palkan** [comment]
> > Do you see "FactoryProf enabled ..." in your console?

> No, i don't

Have you tried other profilers? For example, `TAG_PROF=type rspec ...`. Is there any output?

Maybe, for some reason `test-prof` is not loaded. Try to add `require "test-prof"` in the beginning of your `spec_helper.rb`.

**Comment by nononoy** [comment]
great, after direct requireing in working. 
but
```
FPROF=1 rspec spec
```
caused such an error
```
[TEST PROF INFO] FactoryProf enabled (simple mode)
[TEST PROF ERROR] 
```
FactoryProf generates deadlocks and don't wont to work. Wtih TAG_PROF=type rspec working great. So it seems to be a problem with FactoryProf. Anyway, thanks

**Comment by palkan** [comment]
> [TEST PROF ERROR] 

There is already an issue #42. It's fixed in master and will be released soon.

> FactoryProf generates deadlocks and don't wont to work.

I doubt FactoryProf can cause deadlocks; to do so it should perform DB queries and it does not.

Are there other log messages from TEST PROF?

**Comment by palkan** [comment]
Closed as stale
