### ISSUE TITLE
🤖FactoryBot killed 🙅FactoryGirl

### ISSUE THREAD

**Issue by palkan** [palkan/test-prof#45]
Since FactoryGirl has been renamed to [FactoryBot](https://github.com/thoughtbot/factory_bot) we have to support both names now (for users still using good old FactoryGirl).

I propose to handle this duality by using our own `TestProf::FactoryBot` (just an alias for `FactoryGirl` or `FactoryBot`) everywhere in codebase.

We should also use `factory_bot` by default in our tests and add a separate Travis gemfile for `factory_girl`.

**Comment by benzittlau** [comment]
I'm going to take a swing at this.
