### ISSUE TITLE
Can't enable profilers with ENV vars if spring is in Gemfile

### ISSUE THREAD

**Issue by NIHERASE** [palkan/test-prof#47]
Hi! 
I ran `TEST_STACK_PROF=1 bundle exec rspec` but profiler was not activated because I had spring required in my Gemfile (without `require: false`). The problem seems to be [here](https://github.com/palkan/test-prof/blob/448a6e56d4ff91da5b049605ac1da6c31833560b/lib/test_prof.rb#L62)
If Spring is `defined?` it doesn't actually mean that it's running.

I think it's going to be a common problem because spring tells you (in README) to add it in Gemfile without `require: false`.

**Comment by palkan** [comment]
Hi!

Actually, it doesn't matter whether you add `require: false` for Spring or not, it works differently (just try to do `require "spring"` and you will a LoadError, Bundler ignores it while loading from Gemfile).

And I'm using TestProf along with Spring without any problem.

So, there should be another reason. Have you tried to restart Spring? It might be necessary when adding a new gem.

**Comment by NIHERASE** [comment]
Oh right, it doesn't matter if I have it required or not.

Notice that I ran my tests without spring preloading (even though I do have it in my Gemfile):
`TEST_STACK_PROF=1 bundle exec rspec` 

This way constant `Spring` is defined and `after_fork` callback is never invoked.

I can't see how it would work in this case. Are you always using spring preloading?

**Comment by palkan** [comment]
> This way constant Spring is defined 

Hm, either you have your own `Spring` constant, either you're still using Spring.

Try to run with Spring explicitly disabled: `DISABLE_SPRING=1 TEST_STACK_PROF=1 ...`

**Comment by wpolicarpo** [comment]
Same issue here. I will try to make a reproducible example for that and post here.

**Comment by palkan** [comment]
(Likely) fixed by https://github.com/palkan/test-prof/commit/8094f54f15b3b69b98938e11d35d81036ebb2056 (version 0.4.8).

Please, submit new issue if this doesn't work for you.

There was a problem with Spring detection when using with some gems (e.g. `guard-spring` and `spring-commands-rspec`) which load some `spring` code even if Spring is not running.
