### ISSUE TITLE
README configuration causes error on first run of stackprof

### ISSUE THREAD

**Issue by danielwestendorf** [palkan/test-prof#5]
When running `TEST_STACK_PROF=1 rspec` with the config mentioned in the README

```
TestProf.configure do |config|
  # the directory to put artifacts (reports) in ("tmp" by default)
  config.output_dir = "tmp/test_prof"

  # use unique filenames for reports (by simply appending current timestamp)
  config.timestamps = true

  # color output
  config.color = true
end
```

Produces an error if "tmp/test_prof" doesn't exist. Ideally, TestProf would create this directory if it doesn't exist.

**Comment by palkan** [comment]
Good catch!

And I think it would be better to use "tmp/test_prof" as a default directory.

**Comment by palkan** [comment]
One more thing: don't forget to add a Changelog entry)

Thanks!
