### ISSUE TITLE
ruby 2.2.0 TypeError: nil can't be coerced into Float

### ISSUE THREAD

**Issue by rudolfolah** [palkan/test-prof#60]
### Tell us about your environment

**Ruby Version:** 2.2.0

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** RSpec Core 3.4.1

**TestProf Version:** 0.4.8

### What did you do?

Ran this command:

    RD_PROF=1 bundle exec rspec /path/to/spec_spec.rb

### What did you expect to happen?

Tests would run, slowest let/before blocks would be displayed.

### What actually happened?

Error message:

```
bundler: failed to load command: rspec (/Users/rolah/Code/project/vendor/bundle/ruby/2.2.0/bin/rspec)
TypeError: nil can't be coerced into Float
  /Users/rolah/Code/project/vendor/bundle/ruby/2.2.0/gems/test-prof-0.4.8/lib/test_prof/rspec_dissect/rspec.rb:39:in `+'
  /Users/rolah/Code/project/vendor/bundle/ruby/2.2.0/gems/test-prof-0.4.8/lib/test_prof/rspec_dissect/rspec.rb:39:in `example_finished'
```

**Comment by rudolfolah** [comment]
the fix seems to be to provide a default value:

```ruby
      def example_finished(notification)
        @examples_count += 1
        @examples_time += notification.example.execution_result.run_time || 0 # <-- default value
      end
```

It doesn't crash but at the end of it, all I see is this:

```
Top 5 slowest suites (by `before(:each)` time):

MyController (./spec/controllers/my_controller_spec.rb:3) – 01:20.503 of 01:33.838 (106)

Top 5 slowest suites (by `let` time):

MyController (./spec/controllers/my_controller_spec.rb:3) – 00:00.018 of 01:33.838 (106)
```

(There are only a few let blocks in that test suite so I'm sure the output is correct)

**Comment by palkan** [comment]
Thanks for the report and the PR, @rudolfolah!

It turned out that RSpec 3.4 doesn't provide `run_time` in `example_finished` callback; but actually, we can rely on other callbacks (`example_passed`, `example_failed`) instead, where this information is available.

So, I've another PR which fixes this. Also, it excludes pending/skipped specs from the stats

**Comment by palkan** [comment]
> Is this how it's supposed to look?

Looks like you have a lot of `let!`-s, am I right?

**Comment by rudolfolah** [comment]
in the controller spec there's a few `let` calls, no `let!` though, we also have a lot of `before` blocks. also we have loops of arrays to define more tests. I'm thinking that combining them into one big test would help but still investigating.

I'm wondering if there's a way to see a breakdown of specific spec causing issues; for example we have nested `describe` and `context` blocks, would be cool to see the 2nd level of the tree other than the whole test suite.

**Comment by palkan** [comment]
> I'm wondering if there's a way to see a breakdown of specific spec causing issues; for example we have nested describe and context blocks, would be cool to see the 2nd level of the tree other than the whole test suite.

I was thinking about such kind of report, but haven't found a good way to represent this information yet.

If I understand you correctly, for each example group you want to see something like this:

```
top-level-group
  |
  before/let stats
  |
  level-1 group 1
  |   |
  |    before/let stats
  |   |
  |   level-2 group 1
  |        |
  |        before/let stats
  |
  level-1 group 2
      |
      before/let stats
  ...
```

Am I right?

**Comment by rudolfolah** [comment]
yep exactly; but I guess across a large test suite and multiple files this type of granularity would be too fine-grained?

**Comment by palkan** [comment]
> this type of granularity would be too fine-grained

yeah, that's the problem; need a better way to represent this information. Maybe, some kind of interactive chart (like FactoryFlame report)
