### ISSUE TITLE
bug in before_all with MySql2 adapter

### ISSUE THREAD

**Issue by rudolfolah** [palkan/test-prof#62]
this is the error message I got when trying to use it with MySQL:

```
Failure/Error: ActiveRecord::Base.connection.begin_transaction(joinable: false)

NoMethodError:
   undefined method `begin_transaction' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x007fc049cc3060>
```

**Comment by palkan** [comment]
Hi @rudolfolah!

Which Rails version do you use?

**Comment by rudolfolah** [comment]
- rails 3.2.22.2
- mysql 0.3.21

let me know if you need more info @palkan !

**Comment by palkan** [comment]
Oh, Rails 3.2. It doesn't have this `begin_transaction` method. 

I pushed a commit which adds this functionality to 3.2. Please, try again with GitHub master.

**Comment by rudolfolah** [comment]
seems to work; but we have other issues so I can't tell heh. will try again on a different test suite and let you know the results

**Comment by rudolfolah** [comment]
I tried it again for a different test suite and it failed; TODO: update this post with the error messages that I saw.

**Comment by palkan** [comment]
Closed as stale
