### ISSUE TITLE
Hangs indefinitely after tests

### ISSUE THREAD

**Issue by ghostsquad** [palkan/test-prof#68]
Is there something I need to do to cause TestProf to stop profiling? I'm finding that as soon as I enable this, with only instructions from the Readme. After all tests are done, the process just hangs indefinitely (on our CI server, it was 5 hours before the task was killed).

Is this a known issue?

I'm just using the following in `spec_helper.rb`
```
TestProf.configure do |config|
  config.color = true
end

TestProf::RubyProf.configure do |config|
  config.printer = :call_stack
end
```

and

`TEST_RUBY_PROF=1 bundle exec rspec`

Ruby version: 2.4.3
Latest version of TestProf and RubyProf

**Comment by ghostsquad** [comment]
After further testing with _only_ ruby prof, I've found that issue is there, not with test prof. I'll close this.

**Comment by palkan** [comment]
Yep, RubyProf can significantly slow everything down and easily get stuck. I recommend running it only against a very limited subset of tests.
