### ISSUE TITLE
any_fixture DSL is not usable in Ruby 2.3.4

### ISSUE THREAD

**Issue by BrianHicks** [palkan/test-prof#74]
### Tell us about your environment

**Ruby Version:** 2.3.4

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):** rspec 3.7

**TestProf Version:** 0.5.0

### What did you do?

Tried to `require 'test_prof/any_fixture/dsl'`

### What did you expect to happen?

The DSL to do whatever it needs to so I can `using TestProf::AnyFixture::DSL`

### What actually happened?

```
TypeError: wrong argument type Module (expected Class)
from {my gem path}/lib/test_prof/any_fixture/dsl.rb:13:in `refine'
```

Looks like the test suite works around this:

https://github.com/palkan/test-prof/blob/02b8bc141ece9d3c021df5c6ffa7eb17e3ff10ea/spec/integrations/fixtures/rspec/any_fixture_fixture.rb#L8-L18

Am I expected to do the same in rails_helper or wherever?

**Comment by palkan** [comment]
This limitation is mentioned in [docs](https://test-prof.evilmartians.io/#/any_fixture?id=dsl).

> Am I expected to do the same in rails_helper or wherever?

Yep, you can try to do that. Just keep in mind that it involves _global_ monkey-patching, thus might produce some undesired behaviour.
