### ISSUE TITLE
Unexpected behavior using rubocop autocorrect

### ISSUE THREAD

**Issue by viamin** [palkan/test-prof#75]
### Tell us about your environment

**Ruby Version:**
2.4.4

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
RSpec 3.7.0
FactoryBot 4.10.0
Rails 5.2.0
Rubocop 0.56.0

**TestProf Version:**
0.5.0

### What did you do?
Installed and turned on the Rubocop RSpec/AggregateFailures cop, with AutoCorrect: true

### What did you expect to happen?
My `it { is_expected.to eq(xyz) }` blocks would be aggregated, but not `pending` or `its(:property)` blocks (from the [rspec-its](https://github.com/rspec/rspec-its) gem)

### What actually happened?
`pending { is_expected.to blahblahblah }` blocks were aggregated and activated (no longer pending) and `its(:property_a) { is_expected.to eq(property_a) }` blocks were changed to regular `it` comparisons (no longer checking against the property, but against the object.) Both changes cause the test suite to fail.

**Comment by palkan** [comment]
Thanks for the report!

Fixed in master. Will be included in the next release
