### ISSUE TITLE
How to use test-prof along with spring? 

### ISSUE THREAD

**Issue by dgilperez** [palkan/test-prof#79]
I'm new (and happy) to test-prof, step by step adding more recipes to my suite. I'm trying to run the rspec build using `spring` (previously started with a `bin/rake db:setup` command, for instance, to speed up our CI. But spring seems to ignore the env variables that start the test-prof tools. 

So this works with test-prof, but not with spring:

```
TEST_STACK_PROF=1 FPROF=1 bundle exec rspec spec/tasks
```

And this works with spring, but not with test-prof: 

```
bundle exec spring rspec spec/tasks
# or 
bin/rspec spec/tasks
```

Question is: how to use spring and activate `FPROF` on a particular run?

**Comment by palkan** [comment]
What if you stop Spring and then start it again but running RSpec? I mean:

```
# stop Spring
spring stop
# start it again by running RSpec
bin/rspec
# run RSpec with some test-prof profiler
FPROF=1 bin/rspec
```

Does it work?

I haven't used Spring for a long time but initially I made test-prof to work with it; and it worked just fine.

Probably, it's due to Spring has been started in development env.

**Comment by dgilperez** [comment]
Nope. Second time will use spring normally, but FPROF will not start.

**Comment by palkan** [comment]
@dgilperez Try the current master branch. I've added some Spring-related logs: now, during the first run with Spring you should see `[TEST PROF INFO] Spring detected`, and the following runs should produce smth like `[TEST PROF INFO] Activating EVENT_PROF with Spring.after_fork`.

I've just tried and it works just fine:

```
root@9cbd662d30c8:/app# rspec ./spec/jobs/
[TEST PROF INFO] Spring detected
Running via Spring preloader in process 1004
...

root@9cbd662d30c8:/app# EVENT_PROF=sql.active_record rspec ./spec/jobs/
Running via Spring preloader in process 1020
[TEST PROF INFO] Activating EVENT_PROF with `Spring.after_fork`
[TEST PROF INFO] EventProf enabled (sql.active_record)

[TEST PROF INFO] EventProf results for sql.active_record

...

root@9cbd662d30c8:/app# FPROF=1 rspec ./spec/jobs/
Running via Spring preloader in process 1020
[TEST PROF INFO] Activating FPROF with `Spring.after_fork`
[TEST PROF INFO] FactoryProf enabled (simple mode)

[TEST PROF INFO] Factories usage

 total      top-level                            name

...
```

**Comment by dgilperez** [comment]
Hmm it was not working for a while, and suddenly (same gems) it started today working. I can't relate the origin of the issue. It could have to do with a full ruby reinstall. If the problem comes back I'll reopen. Thanks for help!
