### ISSUE TITLE
Unable to load gem

### ISSUE THREAD

**Issue by george-good** [palkan/test-prof#8]
Hi. Trying to use your gem in my Rails 5 application, and I get the following error:

```
Gem Load Error is: undefined method `shared_context' for RSpec:Module
```

The error occurs at

```
/ruby-2.3.1/gems/test-prof-0.2.0/lib/test_prof/ruby_prof/rspec.rb:4
```

According to the documentation I just need to add the Gem to the project, which I have done. Bundler ran fine, no errors.

Am I required to put some configuration into `rails_helper?`.

Any help with this would be greatly appreciated.

**Comment by palkan** [comment]
Hi, @george-good!

A couple of questions:

- Which RSpec version do you use?

- What command do you use to run tests?

**Comment by george-good** [comment]
Hi @palkan, thanks for the swift response!

Currently using `rspec-rails (3.5.2)`

In this case I was trying to run migrations, they failed due to the load error.

**Comment by palkan** [comment]
Hm, you ran something like that:

```ruby
TEST_RUBY_PROF=1 rake db:migrate
```

I'm trying to figure out, why did TestProf decide to load RSpec integration.

**Comment by george-good** [comment]
I just ran rake `db:migrate RAILS_ENV=test`

**Comment by palkan** [comment]
I have a clue: do you have `module RSpec ... ` or something similar in your application codebase? 

TestProf tries to load RSpec integration due to the presence of the `RSpec` top-level constant (it uses `... if defined?(RSpec)` guard).

Looks like it's defined, but not by `rspec-core` gem.

I've reproduced this behaviour [here](https://travis-ci.org/palkan/test-prof/builds/266227742).

**Comment by palkan** [comment]
Try version 0.2.1 and feel free to re-open the issue if the problem is still there.

**Comment by zdrummond** [comment]
I am getting the same problem. I am using version 0.2.2, and I don't have 'module RSpec' defined anywhere. 

```
/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof/ruby_prof.rb:158:in `initialize': no implicit conversion of Hash into Integer (TypeError)
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof/ruby_prof.rb:158:in `new'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof/ruby_prof.rb:158:in `profile'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof/ruby_prof.rb:136:in `run'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof/ruby_prof.rb:190:in `block in <top (required)>'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof.rb:62:in `block (2 levels) in activate'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof.rb:88:in `activate!'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/test-prof-0.2.2/lib/test_prof.rb:62:in `block in activate'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:238:in `block in invoke_after_fork_callbacks'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:237:in `each'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:237:in `invoke_after_fork_callbacks'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:177:in `block in serve'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:153:in `fork'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:153:in `serve'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
	from /.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by palkan** [comment]
Looks like another problem: this call fails–`::RubyProf::Profile.new(options)`.

Which version of `ruby-prof` do you use? Looks like this functionality [has been added](https://github.com/ruby-prof/ruby-prof/blob/master/CHANGES) only in 0.16.0.

**Comment by zdrummond** [comment]
Looks like ruby-prof (0.15.1), update to 0.16.2 and now it works.

Maybe you can update your Gemspec to require 16?

________________________________

**Comment by palkan** [comment]
> Maybe you can update your Gemspec to require 16?

We don't have `ruby-prof` in our Gemspec, it's an optional dependency.

I will add version checking.

**Comment by palkan** [comment]
> I will add version checking.

Added in https://github.com/palkan/test-prof/commit/a527d7cb01c482963f1cf9d1c8e42216ee0ed94c . Will be published as a part of the next release.
