### ISSUE TITLE
Issue with create_default and traits

### ISSUE THREAD

**Issue by dgilperez** [palkan/test-prof#80]
I have this factory, with a trait that allows changing the association general definition like this: 

```ruby
FactoryBot.define do
  factory :idea do
    association :status, :default

    trait :bla do
      association :status, :bla
    end
  end
end 
```

When I use FactoryDefault to define a default `status` like this in a shared context:

```ruby
shared_context 'My context' do  
  let_it_be(:status) { create :status }

  before do
    set_factory_default :status, status
  end
end
```

And write my spec: 

```ruby
include_context 'My context'

it do
  create :idea #=> is created with the default :status from shared context
  create :idea, :bla #=> is ALSO created with the default :status from shared context
end
```

So in practice `trait :bla` is not used at all, `set_factory_default` is overriding that. This was, at least, surprising and unexpected. I expected the trait behaviour to preveal, since it is explicitly declaring the association.

Is this intented behaviour or is this a 🐛? 

**Ruby Version:** 2.3.7
**Framework Version:** Rspec 3.6
**TestProf Version:** 0.5.0

**Comment by palkan** [comment]
> Is this intented behaviour or is this a 🐛?

It's an intended behaviour. `FactoryDefault` doesn't take into account traits.

I think, we can add this functionality in the following way:

```ruby
# make this record default for the specified traits
create_default(:idea, :my_trait, **params, preserve_traits: true)
# or
set_factory_default(:idea, :my_trait, obj)

# we can set `preserve_traits` globally
TestProf::FactoryDefault.preserve_traits = true

# by default should be false for backward compatibility
```

**Comment by palkan** [comment]
@dgilperez Would you like to propose a PR, btw?

**Comment by dgilperez** [comment]
So I was thinking about the proposed interface, and I was thinking more in the other direction: 

My thinking is that having as we have several different traits per factory, playing with associations, your proposal of defining different defaults for different traits will end up in the need to define one default per trait, and the need to keep remembering that (I will keep forgetting for sure 😄). I'd prefer a way to get my expected behaviour above. 

Something like _use default factory, unless you define it explicitly in a trait_. 

```
# default false for backward compatibility
TestProf::FactoryDefault.preserve_traits = true 

set_factory_default(:idea, obj)

create :idea_thing # =>  sets obj as default
create :idea_thing, :trait_that_changes_idea_association # =>  does not set obj as default
```

I'd definitely like to contribute. But I will not be able until, at least, August. If someone wants to get ahead, that'd be great as well.

**Comment by palkan** [comment]
> defining different defaults for different traits will end up in the need to define one default per trait, and the need to keep remembering that
> I'd prefer a way to get my expected behaviour above.

Agree. Just adding `preserve_traits` should be enough. No trait => use default, has traits => fallback to the default factory behaviour.
