### ISSUE TITLE
Ruby Prof extremely slow after running a large amount of tests

### ISSUE THREAD

**Issue by frostblooded** [palkan/test-prof#90]
The TEST_RUBY_PROF=1 is extremely slow when generating the report after running all rspec tests in the app. I killed it after the process was using 100% CPU and didn't stop for an hour. Is there a way to see what the problem is or to make it verbose in some way to see what is going on?

**Comment by palkan** [comment]
It makes sense to run RubyProf against a random test sample not the whole suite (see [tests sampling](https://test-prof.evilmartians.io/#/tests_sampling)).

RubyProf tracks all the methods invocations and processes them at the end of the run, so, the more tests you have – the more time it would take to crunch the data.

You can also try to [exclude some methods](https://test-prof.evilmartians.io/#/ruby_prof?id=methods-exclusion) from the analysis.

**Comment by frostblooded** [comment]
Oh, that makes sense. My bad. Sorry for missing this in the documentation. :D
