### ISSUE TITLE
ruby_prof/rspec.rb:14:in `example_started': undefined method `example` for #<RSpec::Core::Example:0x00005639a203b8d0

### ISSUE THREAD

**Issue by jumph4x** [palkan/test-prof#98]
Firstly, thank you for the wonderful project and numerous thoughful write-ups. I was really excited to give it a go. 

### Tell us about your environment

ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
rspec-core-2.14.8
rails-4.1.16
factory_girl-4.5.0
test-prof-0.7.1

Also using *spring*.

### What did you do?
Included test-prof in my `test` group, used the `TAG_PROF=type TAG_PROF_EVENT=sql.active_record bin/rspec ` ENV var to run a specific spec. Note, I'm using binstubs and Spring. 

### What did you expect to happen?
Complete without breaking.

### What actually happened?
TestProf seems to be calling the `#example` method on the notification object within the notification callback, whhich ends up resolving to the spec context where this method is undefined, if I'm reading the rror correctly.

**Comment by palkan** [comment]
Thanks for the report!

> rspec-core-2.14.8

I think, that's the problem. The gem is built for RSpec 3+ (some tools 3.2+).
Since we do not require RSpec as a runtime dependency, the installation doesn't fail.

We should add version checks to all RSpec related tools; or, maybe, add support for older RSpecs.

**Comment by jumph4x** [comment]
Right on!

**Comment by jumph4x** [comment]
@palkan That addressed the issue. 
Thank you for a fast response and thank you again for an excellent project. 

Мир, дружба, жвачка.
